# Generated by Django 4.0.3 on 2022-03-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='rolls',
            new_name='rows',
        ),
    ]
