# Generated by Django 4.0.3 on 2022-03-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_rename_rolls_board_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='columns',
            field=models.PositiveIntegerField(default=8, max_length=26),
        ),
    ]
